name: Continuous Integration

on:
  pull_request

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.TEST_SECRET }} | rev
